networks:
  dev:

services:
  postgresDB:
    image: postgres:latest
    container_name: postgresDB
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: FurnitureWebSite
      PGPORT: 5433
    expose:
      - "5433"
    ports:
      - "5433:5433"
    healthcheck:
      test: "pg_isready -h localhost -p 5433 -U admin -d FurnitureWebSite"
      timeout: 10s
      retries: 20
    networks:
      - dev

  accounts_service:
    container_name: accounts_service
    build:
      context: ./Backend/services/accounts

    environment:
      DB_HOST: postgresDB
      DB_PORT: 5433
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: FurnitureWebSite

      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

    ports:
      - "7000:7000"
    depends_on:
      postgresDB:
        condition: service_started
    networks:
      - dev

  furniture_service:
    container_name: furniture_service
    build:
      context: ./Backend/services/furniture
    environment:
      DB_HOST: postgresDB
      DB_PORT: 5433
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: FurnitureWebSite
    ports:
      - "7001:7001"
    depends_on:
      postgresDB:
        condition: service_started
      accounts_service:
        condition: service_started
    networks:
      - dev

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
#      - kafka-ui
      - swagger-ui
    ports:
      - "8080:8080"
    networks:
      - dev

#  kafka-ui:
#    image: provectuslabs/kafka-ui
#    container_name: kafka-ui
#    ports:
#      - "8000:8080"
#    restart: always
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=local
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
#    depends_on:
#      - kafka

#  kafka:
#    image: obsidiandynamics/kafka
#    container_name: kafka
#    restart: "no"
#    ports:
#      - "2181:2181"
#      - "9093:9093"
#    environment:
#      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9093"
#      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9093"
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
#      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
#      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
#      KAFKA_RESTART_ATTEMPTS: "10"
#      KAFKA_RESTART_DELAY: "5"
#      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
#    healthcheck:
#      test: nc -z localhost 29092 || exit
#      interval: 10s
#      timeout: 5s
#      retries: 15

  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      URLS_PRIMARY_NAME: Accounts Service
      URLS: "[ { url: 'http://185.244.219.179:8080/api/accounts/docs/json', name: 'Accounts Service' },
      { url: 'http://185.244.219.179:8080/api/catalog/docs/json', name: 'Furniture service' } ]"
    depends_on:
      - accounts_service
      - furniture_service
    networks:
      - dev
