services:
  postgresDB:
    image: postgres:latest
    container_name: postgresDB
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: FurnitureWebSite
      PGPORT: 5433
    expose:
      - "5433"
    ports:
      - "5433:5433"

  accounts_service:
    container_name: accounts_service
    build:
      context: ./Backend/services/accounts
    ports:
      - "7000:7000"
    depends_on:
      - postgresDB

  furniture_service:
    container_name: furniture_service
    build:
      context: ./Backend/services/furniture
    ports:
      - "7001:7001"
    depends_on:
      - postgresDB
      - accounts_service

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - furniture_service
      - accounts_service
      - postgresDB
    ports:
      - "8080:8080"