services:
  postgresDB:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: FurnitureWebSite
    ports:
      - "5433:5433"

  accounts_service:
    develop:
      watch:
        - action: rebuild
          path: ./services/accounts
    build:
      context: ./services/accounts
    ports:
      - "7000:7000"
    depends_on:
      - postgresDB