"""change email and password of admin

Revision ID: 3d2cee66afc9
Revises: 460a8fa11fcf
Create Date: 2024-10-22 13:50:49.952292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d2cee66afc9'
down_revision: Union[str, None] = '460a8fa11fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'email',
               existing_type=sa.CHAR(length=20),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('admins', 'password',
               existing_type=sa.CHAR(length=20),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'password',
               existing_type=sa.String(),
               type_=sa.CHAR(length=20),
               existing_nullable=False)
    op.alter_column('admins', 'email',
               existing_type=sa.String(),
               type_=sa.CHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
