"""change user token model

Revision ID: 42e7c40a4981
Revises: 196fb5c1968e
Create Date: 2024-10-19 01:37:59.196845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e7c40a4981'
down_revision: Union[str, None] = '196fb5c1968e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tokens', sa.Column('jwt_datetime', sa.DateTime(), nullable=False))
    op.add_column('user_tokens', sa.Column('expiry_datetime', sa.DateTime(), nullable=False))
    op.drop_column('user_tokens', 'expiry_date')
    op.drop_column('user_tokens', 'creating_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tokens', sa.Column('creating_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('user_tokens', sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('user_tokens', 'expiry_datetime')
    op.drop_column('user_tokens', 'jwt_datetime')
    # ### end Alembic commands ###
