"""change admin token model

Revision ID: 460a8fa11fcf
Revises: dc08b62f5d61
Create Date: 2024-10-20 23:58:54.500997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460a8fa11fcf'
down_revision: Union[str, None] = 'dc08b62f5d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_tokens', sa.Column('admin_id', sa.BigInteger(), nullable=False))
    op.add_column('admin_tokens', sa.Column('jwt_datetime', sa.DateTime(), nullable=False))
    op.add_column('admin_tokens', sa.Column('expiry_datetime', sa.DateTime(), nullable=False))
    op.drop_constraint('admin_tokens_user_id_key', 'admin_tokens', type_='unique')
    op.drop_constraint('admin_tokens_user_id_fkey', 'admin_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'admin_tokens', 'admins', ['admin_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('admin_tokens', 'creating_date')
    op.drop_column('admin_tokens', 'user_id')
    op.drop_column('admin_tokens', 'expiry_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_tokens', sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('admin_tokens', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('admin_tokens', sa.Column('creating_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'admin_tokens', type_='foreignkey')
    op.create_foreign_key('admin_tokens_user_id_fkey', 'admin_tokens', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_unique_constraint('admin_tokens_user_id_key', 'admin_tokens', ['user_id'])
    op.drop_column('admin_tokens', 'expiry_datetime')
    op.drop_column('admin_tokens', 'jwt_datetime')
    op.drop_column('admin_tokens', 'admin_id')
    # ### end Alembic commands ###
