"""change user token model

Revision ID: dc08b62f5d61
Revises: 42e7c40a4981
Create Date: 2024-10-19 01:42:18.219254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc08b62f5d61'
down_revision: Union[str, None] = '42e7c40a4981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_tokens_user_id_key', 'user_tokens', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_tokens_user_id_key', 'user_tokens', ['user_id'])
    # ### end Alembic commands ###
