"""add tag to catalog model

Revision ID: 37ca965edbfe
Revises: 69a2ba0d1355
Create Date: 2024-10-23 15:03:49.719346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37ca965edbfe'
down_revision: Union[str, None] = '69a2ba0d1355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogs', sa.Column('tag', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'catalogs', ['tag'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalogs', type_='unique')
    op.drop_column('catalogs', 'tag')
    # ### end Alembic commands ###
