"""add tags for types and products

Revision ID: 7c39addf56ab
Revises: f2ebcdf85b72
Create Date: 2024-12-02 23:22:26.653584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c39addf56ab'
down_revision: Union[str, None] = 'f2ebcdf85b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tag', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'products', ['tag'])
    op.add_column('types', sa.Column('tag', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'types', ['tag'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'types', type_='unique')
    op.drop_column('types', 'tag')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'tag')
    # ### end Alembic commands ###
