user_token: OTY3NmVjYWYtZTJhNC00NzNhLTgwM2YtZGY3OTBkYTM3YWFhXzcxMTQ=

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=

database:
  host: localhost
  port: 5432
  user: admin
  password: admin
  database: FurnitureWebSite
