const CHANGE_VISIBILITY = 'CHANGE_VISIBILITY'
const TOGGLE_MESSENGERS = 'TOGGLE_MESSENGERS'
const TOGGLE_EMOJI = 'TOGGLE_EMOJI'
const INIT_SESSION = 'INIT_SESSION'
const INIT_DEVICE = 'INIT_DEVICE'
const SHOW_CHAT = 'SHOW_CHAT'
const CHANGE_CONTACT_FORM_STATE = 'CHANGE_CONTACT_FORM_STATE'
const LOAD_MESSAGES = 'LOAD_MESSAGES'
const SET_MESSAGE = 'SET_MESSAGE'
const UPDATE_MESSAGE = 'UPDATE_MESSAGE'
const DELETE_MESSAGE = 'DELETE_MESSAGE'
const SET_MANAGER = 'SET_MANAGER'
const SET_USER = 'SET_USER'
const VIEW_IMAGE = 'VIEW_IMAGE'
const CLOSE_IMAGE_VIEW = 'CLOSE_IMAGE_VIEW'
const UPDATE_FILE = 'UPDATE_FILE'
const ADD_FILES = 'ADD_FILES'
const REMOVE_FILE = 'REMOVE_FILE'
const CLEAR_FILES = 'CLEAR_FILES'
const SET_MESSAGE_READ = 'SET_MESSAGE_READ'
const DISABLE_CONTACT_FORM = 'DISABLE_CONTACT_FORM'
const SET_DOMAIN_CONFIG = 'SET_DOMAIN_CONFIG'
const SET_OFFLINE_STATUS = 'SET_OFFLINE_STATUS'

export {
    CHANGE_VISIBILITY,
    TOGGLE_MESSENGERS,
    TOGGLE_EMOJI,
    INIT_SESSION,
    INIT_DEVICE,
    SHOW_CHAT,
    CHANGE_CONTACT_FORM_STATE,
    LOAD_MESSAGES,
    SET_MESSAGE,
    UPDATE_MESSAGE,
    DELETE_MESSAGE,
    SET_MESSAGE_READ,
    SET_MANAGER,
    SET_USER,
    VIEW_IMAGE,
    CLOSE_IMAGE_VIEW,
    UPDATE_FILE,
    ADD_FILES,
    REMOVE_FILE,
    CLEAR_FILES,
    DISABLE_CONTACT_FORM,
    SET_DOMAIN_CONFIG,
    SET_OFFLINE_STATUS
}



// WEBPACK FOOTER //
// ./src/store/mutations.js