name: Master Workflow - Build and deploy to production

on:
  push:
    branches:
      - main

jobs:
  test_accounts_service:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: PetPal
        ports:
          - 5432:5432
        options:
          --health-cmd "pg_isready -U admin"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Create virtual environment
        working-directory: accounts
        run: python -m venv venv

      - name: Activate virtual environment
        working-directory: accounts
        run: source venv/bin/activate

      - name: Install Python dependencies
        working-directory: accounts
        run: pip install -r requirements.txt

      - name: Add environment variables
        working-directory: accounts
        run: |
          echo "DB_USER=admin" >> .env
          echo "DB_PASSWORD=admin" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_NAME=PetPal" >> .env

      - name: Start migrations
        working-directory: accounts
        run: alembic upgrade head

      - name: Run tests
        working-directory: accounts
        run: pytest tests

  deploy:
    needs: test_accounts_service
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with docker-compose
        run: docker-compose build

      - name: Up docker-compose
        run: docker-compose up