name: Build and Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  setup_services:
    runs-on: ubuntu-latest

    services:
      postgresDB:
        image: postgres:latest
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: FurnitureWebSite
        ports:
          - 5433:5433

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Create virtual environment
        working-directory: Backend/services/accounts
        run: python -m venv venv

      - name: Activate virtual environment
        working-directory: Backend/services/accounts
        run: source venv/bin/activate

      - name: Install Python dependencies
        working-directory: Backend/services/accounts
        run: pip install -r requirements.txt

  test_accounts_service:
    runs-on: ubuntu-latest
    needs:
      - setup_services
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Activate virtual environment
        working-directory: Backend/services/accounts
        run: source venv/bin/activate

      - name: Run tests
        working-directory: Backend/services/accounts
        run: pytest tests