name: Build and Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Check changes files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  deploy:
    needs:
      - check

    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.1.0
          legacy: true
      - run: docker-compose --version

      - name: Build project
        run: docker-compose -f ./docker-compose.yml up